sudo:              false

addons:
  apt:
    packages:
      - openjdk-8-jdk

language:          generic

branches:
  - master

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/jython-builds.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"

install:
  - git clone https://github.com/jythontools/jython.git jython2 && cd jython2 && ant installer && ant standalone
  - java -jar jython-standalone.jar getver.py > $TRAVIS_BUILD_DIR/build/2/info.txt
  - cd ..
  - git clone https://github.com/jythontools/jython.git jython3 && cd jython3 && ant installer && ant standalone
  - java -jar jython-standalone.jar getver.py > $TRAVIS_BUILD_DIR/build/3/info.txt
  - cd ..

script:
  - cd $TRAVIS_BUILD_DIR/build/2
  - cp $TRAVIS_BUILD_DIR/jython2/jython-standalone.jar standalone.jar
  - java -jar jython-installer.jar --silent --type standalone --verbose && dir && mv jython.jar standalone.jar

notifications:
  email:           false
